### ISSUE TITLE
Epic API Checklist

### ISSUE THREAD

**Issue by sisby-folk** [sisby-folk/switchy#27]
This is an epic checklist for normally-obvious API endpoints for operating switchy programmatically.   

When this is more complete, stuff should be broken in order to move it into more logical files.

switchy-core
- Get:
  - [x] all module identifiers
  - [x] whether a module is registered by ID
  - [x] editable by module ID
  - [x] default by module ID
  - [x] warning message by module ID
  - [x] apply dependencies by module ID
- Get (with SwitchyPresets):
  - [x] Preset name list
  - [x] `modules` map
    - [x] Disabled module IDs
    - [x] Enabled module IDs
    - [x] Enabled modules Text
    - [x] Enabled module string list
  - [x] Current preset name
  - [x] `SwitchyPreset` object by name (**impl access**)
  - [x] Modules by preset name (**impl access**)
  - [x] Modules by module id (**impl access**)
  - [x] Module by module id and preset name (**impl access**)
  - [x] Last Switchy command entered
- Document:
    - [x] A specific module
- Change (with a player)
  - [x] Add an empty preset by name
  - [x] Rename a preset
  - [x] Delete a preset by name
  - [x] Current preset by name
  - [x] Import a preset map
  - [x] Mutate a preset of modules (ID+Mutator map OR <ID,Module> BiConsumer mutator)
- Change (with a player and module id)
  - [x] Enable a module
  - [x] Disable a module
  - [x] Mutate a module by preset name (w/ duck path)
  - [x] Mutate a module on all presets (name+Mutator map OR <name,Module>)
- Listen For:
  - [x] Switches
    - [x] In-game switch
    - [x] Game-join switch (no previous preset)
    - [x] Game-leave switch (no current preset)

switchy-client
   - Get:
     - [x] Whether the client is connected to a switchy server
     - [x] `SwitchyDisplayPresets` for the client player
     - [x] Preset NBT for the client player (exported) w/ exclusions
     - [x] Preset dat path for the client player (exported)
     - [x] Available dat files for import
   - Get (with a SwitchyDisplayPresets):
     - [x] Preset name list
     - [x] `modules` map
- Change
  - [x] Add an empty preset by name
  - [x] Rename a preset
  - [x] Delete a preset by name
  - [x] Current preset by name
  - [x] Enable a module
  - [x] Disable a module
  - [x] Import preset NBT
- Listen For:
  - [x] Switches
    - [x] In-game switch
    - [x] Game-join switch (no previous preset)
    - [x] Game-leave switch (no current preset)

**Comment by sisby-folk** [comment]
Feature complete as of 8d43d62 - to be fully documented.

**Comment by sisby-folk** [comment]
Documented in 77c55a6
